
modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="cardcraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="CardCraft" #mandatory

authors="RedRoseWarrior for porting to 1.16.5" #optional
description='''
Adds cards into mc. also a modding api

'''
[[dependencies.cardcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cardcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
